
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: MiB Open Science
subtitle: "Conceptpagina"
#Deployment
url: "http://mibopenscience.github.io" # the base hostname & protocol for your site
baseurl: "/"
#Local development
#url: "http://localhost" # the base hostname & protocol for your site
#baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

collections_dir: uvcollections
collections:
  c00helpdesk:
    output: true
  c01toolbox:
    #output: true
  c02training:
    #output: true
  c03about:
    #output: true
  